# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: f9becabeab700b6ad2254acdce58f1fa4f33f67cfae8a00ab4adb4faf0a8bae44944566d1a77b910ce1f546c7193be0ddefe43bcac3c7d8d682b0e5662030e64

test:
  domain_name: example.com 
  secret_key_base: 98a00d8ae5c95baf23b9f8dd07ec7d3df09a3af41d4520267b7bc3d7ab067bde09f4265896d0ace0a1540fadea5585e0fd7fbaf7d3f5e8d23bd301d5a9852222

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["SECRET_TOKEN"] %>
