# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# user = CreateAdminService.new.call
# puts 'CREATED ADMIN USER: ' << user.email
# Environment variables (ENV['...']) can be set in the file .env file.

Poster.create(name: "The Great Koala")
Poster.create(name: "Obi-Wan")
Poster.create(name: "Luke")
Poster.create(name: "Capt. Firmus Piett")
Poster.create(name: "Adm. Kendel Ozzel")
Poster.create(name: "Darth Vader")
Poster.create(name: "Gen. Maximilian Veers")
Poster.create(name: "Admiral Piett")
Poster.create(name: "Emperor Palpatine")
Poster.create(name: "Yoda")

MessageItem.create(message: "[Luke is stranded out in a harsh snowstorm.]", poster: Poster.find_by_name("The Great Koala"))
MessageItem.create(message: "[voice comes out of nowhere] Luke. Luke!", poster: Poster.find_by_name("Obi-Wan"))
MessageItem.create(message: "[weakly] Ben?", poster: Poster.find_by_name("Luke"))
MessageItem.create(message: "You will go to the Dagobah system.", poster: Poster.find_by_name("Obi-Wan"))
MessageItem.create(message: "Dagobah system?", poster: Poster.find_by_name("Luke"))
MessageItem.create(message: "There you will learn from Yoda, the Jedi Master who instructed me.", poster: Poster.find_by_name("Obi-Wan"))
MessageItem.create(message: "[Aboard the Super Star Destroyer Executor, Captain Firmus Piett reports to Admiral Kendel Ozzel.]", poster: Poster.find_by_name("The Great Koala"))
MessageItem.create(message: "Admiral!", poster: Poster.find_by_name("Capt. Firmus Piett"))
MessageItem.create(message: "Yes, Captain?", poster: Poster.find_by_name("Adm. Kendel Ozzel"))
MessageItem.create(message: "I think we've got something, sir. The report is only a fragment, from a probe droid in the Hoth system, but it's the best lead we have.", poster: Poster.find_by_name("Capt. Firmus Piett"))
MessageItem.create(message: "[growing impatient] We have thousands of probe droids searching the galaxy. I want proof, not leads!", poster: Poster.find_by_name("Adm. Kendel Ozzel"))
MessageItem.create(message: "The visuals indicate life readings.", poster: Poster.find_by_name("Capt. Firmus Piett"))
MessageItem.create(message: "It could mean anything! If we followed up every lead...", poster: Poster.find_by_name("Adm. Kendel Ozzel"))
MessageItem.create(message: "But sir, the Hoth system is supposed to be devoid of human forms.", poster: Poster.find_by_name("Capt. Firmus Piett"))
MessageItem.create(message: "[approaching the two officers after hearing their conversation] You've found something?", poster: Poster.find_by_name("Darth Vader"))
MessageItem.create(message: "Yes, my Lord. [shows Vader the location of the power generator on Hoth]", poster: Poster.find_by_name("Capt. Firmus Piett"))
MessageItem.create(message: "That's it. The Rebels are there.", poster: Poster.find_by_name("Darth Vader"))
MessageItem.create(message: "[annoyed] My Lord, there are so many uncharted settlements. It could be smugglers; it could be pirates; it could be...", poster: Poster.find_by_name("Adm. Kendel Ozzel"))
MessageItem.create(message: "That is the system! And I am sure Skywalker is with them. Set your course for the Hoth system!! [turns to General Maximilian Veers] General Veers, prepare your men!!", poster: Poster.find_by_name("Darth Vader"))
MessageItem.create(message: "[Darth Vader emerges from an egg-like meditation chamber to receive a report from General Maximilian Veers.]", poster: Poster.find_by_name("The Great Koala"))
MessageItem.create(message: "What is it, General?", poster: Poster.find_by_name("Darth Vader"))
MessageItem.create(message: "My Lord, the fleet has moved out of lightspeed. Com-Scan has detected an energy field protecting an area of the sixth planet of the Hoth system. The field is strong enough to deflect any bombardment.", poster: Poster.find_by_name("Gen. Maximilian Veers"))
MessageItem.create(message: "[Angrily] The Rebels are alerted to our presence. Admiral Ozzel came out of lightspeed too close to the system.", poster: Poster.find_by_name("Darth Vader"))
MessageItem.create(message: "He felt surprise was wiser‚Äî", poster: Poster.find_by_name("Gen. Maximilian Veers"))
MessageItem.create(message: "He is as clumsy as he is stupid. General, prepare your troops for a surface attack.", poster: Poster.find_by_name("Darth Vader"))
MessageItem.create(message: "Yes, my Lord. [bows and leaves quickly]", poster: Poster.find_by_name("Gen. Maximilian Veers"))
MessageItem.create(message: "[Darth Vader turns to a nearby screen and calls up Admiral Kendel Ozzel and Captain Firmus Piett.]", poster: Poster.find_by_name("The Great Koala"))
MessageItem.create(message: "Lord Vader, the fleet has moved out of lightspeed and we're preparing to [begins choking]", poster: Poster.find_by_name("Adm. Kendel Ozzel"))
MessageItem.create(message: "You have failed me for the last time, Admiral. Captain Piett.", poster: Poster.find_by_name("Darth Vader"))
MessageItem.create(message: "[nervously] Yes, my Lord.", poster: Poster.find_by_name("Capt. Firmus Piett"))
MessageItem.create(message: "Make ready to land our troops beyond their energy field, then deploy the fleet so that nothing gets off the system. You are in command now, Admiral Piett.", poster: Poster.find_by_name("Darth Vader"))
MessageItem.create(message: "[sees a dead Ozzel collapse] Thank you, Lord Vader.", poster: Poster.find_by_name("Admiral Piett"))
MessageItem.create(message: "[kneeling before Emperor Palpatine's hologram] What is thy bidding, my master?", poster: Poster.find_by_name("Darth Vader"))
MessageItem.create(message: "There is a great disturbance in the Force.", poster: Poster.find_by_name("Emperor Palpatine"))
MessageItem.create(message: "I have felt it.", poster: Poster.find_by_name("Darth Vader"))
MessageItem.create(message: "We have a new enemy. The young Rebel who destroyed the Death Star. I have no doubt this boy is the offspring of Anakin Skywalker.", poster: Poster.find_by_name("Emperor Palpatine"))
MessageItem.create(message: "How is that possible?", poster: Poster.find_by_name("Darth Vader"))
MessageItem.create(message: "Search your feelings, Lord Vader. You will know it to be true. He could destroy us.", poster: Poster.find_by_name("Emperor Palpatine"))
MessageItem.create(message: "He's just a boy. Obi-Wan can no longer help him.", poster: Poster.find_by_name("Darth Vader"))
MessageItem.create(message: "The Force is strong with him. The son of Skywalker must not become a Jedi.", poster: Poster.find_by_name("Emperor Palpatine"))
MessageItem.create(message: "If he could be turned, he would become a powerful ally.", poster: Poster.find_by_name("Darth Vader"))
MessageItem.create(message: "[intrigued] Yes... He would be a great asset. Can it be done?", poster: Poster.find_by_name("Emperor Palpatine"))
MessageItem.create(message: "He will join us or die, master.", poster: Poster.find_by_name("Darth Vader"))
MessageItem.create(message: "[Luke sees his X-Wing is about to sink into the bog]", poster: Poster.find_by_name("The Great Koala"))
MessageItem.create(message: "Oh, no! We'll never get it out now!", poster: Poster.find_by_name("Luke"))
MessageItem.create(message: "So certain, are you? Always with you, it cannot be done. Hear you nothing that I say?", poster: Poster.find_by_name("Yoda"))
MessageItem.create(message: "Master, moving stones around is one thing, but this is... totally different!", poster: Poster.find_by_name("Luke"))
MessageItem.create(message: "No! No different! Only different in your mind. You must unlearn what you have learned.", poster: Poster.find_by_name("Yoda"))
MessageItem.create(message: "All right, I'll give it a try.", poster: Poster.find_by_name("Luke"))
MessageItem.create(message: "No! Try not. Do... or do not. There is no try.", poster: Poster.find_by_name("Yoda"))
MessageItem.create(message: "[Luke tries to use the Force to levitate his X-Wing out of the bog, but fails in his attempt.]", poster: Poster.find_by_name("The Great Koala"))
MessageItem.create(message: "I can't. It's too big.", poster: Poster.find_by_name("Luke"))
MessageItem.create(message: "Size matters not. Look at me. Judge me by my size, do you? Hmm? Hmm. And well you should not. For my ally is the Force, and a powerful ally it is. Life creates it, makes it grow. Its energy surrounds us and binds us. Luminous beings are we, not this crude matter. You must feel the Force around you; here, between you, me, the tree, the rock, everywhere, yes. Even between the land and the ship.", poster: Poster.find_by_name("Yoda"))
MessageItem.create(message: "You want the impossible. [sees Yoda use the Force to levitate the X-Wing out of the bog and gets flustered when he does it] I don't... I don't believe it!", poster: Poster.find_by_name("Luke"))
MessageItem.create(message: "That is why you fail.", poster: Poster.find_by_name("Yoda"))